[package]
name = "markdown-preview-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
clap = { version = "4.1.8", features = ["derive"] }
markdown = "1.0.0-alpha.7"
serde_json = "1.0.94"
