[package]
name = "markdown-preview-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
clap = { version = "4.1.8", features = ["derive"] }
katex = "0.4.6"
markdown = "1.0.0-alpha.7"
regex = "1.7.1"
serde = "1.0.156"
serde_json = "1.0.94"
serde_yaml = "0.9.19"
yaml-rust = "0.4.5"
