[package]
name = "markdown-preview-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.3.1"
actix-web-actors = "4.2.0"
axum = "0.6.12"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
futures-channel = "0.3.28"
futures-util = "0.3.28"
katex = "0.4.6"
latex2mathml = "0.2.3"
lazy_static = "1.4.0"
markdown-it = "0.4.0"
memoize = "0.4.0"
rand = "0.8.5"
regex = "1.7.1"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
substring = "1.4.5"
tokio = { version = "1.27.0", features = ["full"] }
tokio-tungstenite = "0.18.0"
tower-service = "0.3.2"
tungstenite = "0.18.0"
yaml-rust = "0.4.5"

[dev-dependencies]
axum-macros = "0.3.7"
