name: Build on Linux

on:
  push:
    branches: main

jobs:
  build-web:
    name: Build Webview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          corepack enable
          cd src_web && yarn
          yarn build
          tar -C build -czvf webview.tar.gz ./
      - name: 'Upload webview build as artifact'
        uses: actions/upload-artifact@v3
        with:
          name: webview
          path: src_web/webview.tar.gz

  build-linux-generic:
    name: Build Linux (generic)
    needs: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the webview
        uses: actions/download-artifact@v3
        with:
          name: webview

      - name: 'Build generic version (x86_64)'
        run: |
          mkdir -p assets/web_build
          tar --version
          file webview.tar.gz
          tar -xzvf webview.tar.gz -C assets/web_build
          ls assets/web_build
          

      - name: 'Upload generic version as artifact'
        uses: actions/upload-artifact@v3
        with:
          name: linux_x86_64_generic
          path: build/*
        
          #      - name: Build (Arch Linux x86_64)
          #        uses: hapakaien/archlinux-package-action@v2
          #        with:
          #          aur: true
          #          update_archlinux_keyring: false
          #          pkgver: ${{ steps.previoustag.outputs.tag }}
          #          path: buildfiles/archlinux/markdown-preview-server
